# Generated by Django 2.0.2 on 2018-02-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('unit', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
            ],
        ),
    ]
